repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
      - id: remove-tabs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.46.0
    hooks:
      - id: markdownlint-fix
        args:
          - --ignore
          - LICENSE.md
          - --ignore
          - context/references/*
          - --disable
          - MD033 # Inline HTML
          - MD036 # Emphasis used instead of a header
          - --
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.46.0
    hooks:
      - id: markdownlint-fix
        name: markdownlint-fix--references
        files: context/references/.*?\.md
        args:
          - --disable
          - MD013 # Line length
          - MD033 # Inline HTML
          - MD036 # Emphasis used instead of a header
          - --
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.15
    hooks:
      - id: uv-lock